### ISSUE TITLE
Why Apache License ???

### ISSUE THREAD

**Issue by ghost** [DeepLearningKit/DeepLearningKit#12]
I've been looking at a lot of MIT licensed based Swift AI and Deep Learning efforts and they are more than sufficient to do good work.

It begs the question, why the Apache License? Why not the MIT license?

If I build an App that uses the Google Cloud Platform and DeepLearningKit, aren't I under obligation, more obligation than MIT license, that prohibits my sale of the application or other requirements?

**Comment by atveit** [comment]
to my knowledge Apache 2.0 is a nice open source licence with few strings attached.
