### ISSUE TITLE
Add UIImage to RGB converter

### ISSUE THREAD

**Issue by mfentross** [DeepLearningKit/DeepLearningKit#8]
Quoting the [contribute page](http://deeplearningkit.org/contribute/): 

> DeepLearningKit is missing basic conversion from e.g. UIImage to RGB (the example network supports 32x32x3 CIFAR RGB Image Format, but has no conversion from UIImage to it). Check out e.g. Drawing Images From Pixel Data – In Swift and Image Processing in iOS Part 1: Raw Bitmap Modification for inspiration.

**Comment by atveit** [comment]
Hi @torb - do you have time for this?

**Comment by several27** [comment]
I guess something like that could be used.
I haven't created pull request, because I didn't know in which file put it.
Inspired by: https://github.com/scottsievert/swix/blob/master/swix/swix/swix/matrix/m-image.swift#L81

UIImage to four (R, G, B, A) float matrices converter:

``` swift
func imageToMatrix(image: UIImage) -> ([Float], [Float], [Float], [Float])
{
    let imageRef = image.CGImage
    let width = CGImageGetWidth(imageRef)
    let height = CGImageGetHeight(imageRef)
    let colorSpace = CGColorSpaceCreateDeviceRGB()
    let bytesPerPixel = 4
    let bytesPerRow:UInt = UInt(bytesPerPixel) * UInt(width)
    let bitsPerComponent:UInt = 8
    let pix = Int(width) * Int(height)
    let count:Int = 4 * Int(pix)

    // Pulling the color out of the image
    let rawData = UnsafeMutablePointer<UInt8>.alloc(4 * width * height)
    let temp = CGImageAlphaInfo.PremultipliedLast.rawValue
    let context = CGBitmapContextCreate(rawData, Int(width), Int(height), Int(bitsPerComponent), Int(bytesPerRow), colorSpace, temp)
    CGContextDrawImage(context, CGRectMake(0, 0, CGFloat(width), CGFloat(height)), imageRef)

    // Unsigned char to double conversion
    var rawDataArray: [Float] = Array(count: count, repeatedValue: 0.0)
    vDSP_vfltu8(rawData, vDSP_Stride(1), &rawDataArray, 1, vDSP_Length(count))

    // Indices matrix
    var i: [Float] = Array(count: pix, repeatedValue: 0.0)
    var min: Float = 0.0
    var step: Float = 4.0
    vDSP_vramp(&min, &step, &i, vDSP_Stride(1), vDSP_Length(i.count))

    func increaseMatrix(var matrix: [Float]) -> [Float]
    {
        var increaser: Float = 1.0
        vDSP_vsadd(&matrix, vDSP_Stride(1), &increaser, &matrix, vDSP_Stride(1), vDSP_Length(i.count))

        return matrix
    }

    // Red matrix
    var r: [Float] = Array(count: pix, repeatedValue: 0.0)
    vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &r, vDSP_Stride(1), vDSP_Length(r.count))

    increaseMatrix(i)
    // Green matrix
    var g: [Float] = Array(count: pix, repeatedValue: 0.0)
    vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &g, vDSP_Stride(1), vDSP_Length(g.count))

    increaseMatrix(i)
    // Blue matrix
    var b: [Float] = Array(count: pix, repeatedValue: 0.0)
    vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &b, vDSP_Stride(1), vDSP_Length(b.count))

    increaseMatrix(i)
    // Alpha matrix
    var a: [Float] = Array(count: pix, repeatedValue: 0.0)
    vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &a, vDSP_Stride(1), vDSP_Length(a.count))

    return (r, g, b, a)
}
```

**Comment by ashmanov** [comment]
I've tried this code, but it wrote same values to each of RGBA channels. Here's the fixed code:

```
func imageToMatrix(image: UIImage) -> ([Float], [Float], [Float], [Float])
{
    let imageRef = image.CGImage
    let width = CGImageGetWidth(imageRef)
    let height = CGImageGetHeight(imageRef)
    let colorSpace = CGColorSpaceCreateDeviceRGB()
    let bytesPerPixel = 4
    let bytesPerRow:UInt = UInt(bytesPerPixel) * UInt(width)
    let bitsPerComponent:UInt = 8
    let pix = Int(width) * Int(height)
    let count:Int = 4 * Int(pix)

    // Pulling the color out of the image
    let rawData = UnsafeMutablePointer<UInt8>.alloc(4 * width * height)
    let temp = CGImageAlphaInfo.PremultipliedLast.rawValue
    let context = CGBitmapContextCreate(rawData, Int(width), Int(height), Int(bitsPerComponent), Int(bytesPerRow), colorSpace, temp)
    CGContextDrawImage(context, CGRectMake(0, 0, CGFloat(width), CGFloat(height)), imageRef)

    // Unsigned char to double conversion
    var rawDataArray: [Float] = Array(count: count, repeatedValue: 0.0)
    vDSP_vfltu8(rawData, vDSP_Stride(1), &rawDataArray, 1, vDSP_Length(count))

    // Indices matrix
    var i: [Float] = Array(count: pix, repeatedValue: 0.0)
    var min: Float = 0.0
    var step: Float = 4.0
    vDSP_vramp(&min, &step, &i, vDSP_Stride(1), vDSP_Length(i.count))

    func increaseMatrix(var matrix: [Float]) -> [Float]
    {
        var increaser: Float = 1.0
        vDSP_vsadd(&matrix, vDSP_Stride(1), &increaser, &matrix, vDSP_Stride(1), vDSP_Length(i.count))

        return matrix
    }

    // Red matrix
    var r: [Float] = Array(count: pix, repeatedValue: 0.0)
    vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &r, vDSP_Stride(1), vDSP_Length(r.count))

    increaseMatrix(i)
    min = 1.0
    vDSP_vramp(&min, &step, &i, vDSP_Stride(1), vDSP_Length(i.count))
    // Green matrix
    var g: [Float] = Array(count: pix, repeatedValue: 0.0)
    vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &g, vDSP_Stride(1), vDSP_Length(g.count))

    increaseMatrix(i)
    min = 2.0
    vDSP_vramp(&min, &step, &i, vDSP_Stride(1), vDSP_Length(i.count))
    // Blue matrix
    var b: [Float] = Array(count: pix, repeatedValue: 0.0)
    vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &b, vDSP_Stride(1), vDSP_Length(b.count))

    increaseMatrix(i)
    min = 3.0
    vDSP_vramp(&min, &step, &i, vDSP_Stride(1), vDSP_Length(i.count))
    // Alpha matrix
    var a: [Float] = Array(count: pix, repeatedValue: 0.0)
    vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &a, vDSP_Stride(1), vDSP_Length(a.count))

    return (r, g, b, a)
}
```

**Comment by atveit** [comment]
Thanks for solutions, please create pull requests next time :)

I've added support for this myself, using https://github.com/kNeerajPro/ImagePixelFun - have a look at https://github.com/DeepLearningKit/DeepLearningKit/commit/b4c47d238bb26f51af1e1e5c9cd664cb202aaa83

Will keep this ticket open until I've added a blog post about it.

Amund

**Comment by ashmanov** [comment]
There was a bug, here is the working code:

`func imageToMatrix(image: UIImage) -> ([Float], [Float], [Float], [Float])
{
	let imageRef = image.CGImage
	let width = CGImageGetWidth(imageRef)
	let height = CGImageGetHeight(imageRef)
	let colorSpace = CGColorSpaceCreateDeviceRGB()
	let bytesPerPixel = 4
	let bytesPerRow:UInt = UInt(bytesPerPixel) * UInt(width)
	let bitsPerComponent:UInt = 8
	let pix = Int(width) * Int(height)
	let count:Int = 4 * Int(pix)
	
	// Pulling the color out of the image
	let rawData = UnsafeMutablePointer<UInt8>.alloc(4 * width * height)
	let temp = CGImageAlphaInfo.PremultipliedLast.rawValue
	let context = CGBitmapContextCreate(rawData, Int(width), Int(height), Int(bitsPerComponent), Int(bytesPerRow), colorSpace, temp)
	CGContextDrawImage(context, CGRectMake(0, 0, CGFloat(width), CGFloat(height)), imageRef)
	
	// Unsigned char to double conversion
	var rawDataArray: [Float] = Array(count: count, repeatedValue: 0.0)
	vDSP_vfltu8(rawData, vDSP_Stride(1), &rawDataArray, 1, vDSP_Length(count))
	
	// Indices matrix
	var i: [Float] = Array(count: pix, repeatedValue: 0.0)
	var min: Float = 0.0
	var step: Float = 4.0
	vDSP_vramp(&min, &step, &i, vDSP_Stride(1), vDSP_Length(i.count))
	
	func increaseMatrix(var matrix: [Float]) -> [Float]
	{
		var increaser: Float = 1.0
		vDSP_vsadd(&matrix, vDSP_Stride(1), &increaser, &matrix, vDSP_Stride(1), vDSP_Length(i.count))
		
		return matrix
	}
	
	// Red matrix
	var r: [Float] = Array(count: pix, repeatedValue: 0.0)
	vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &r, vDSP_Stride(1), vDSP_Length(r.count))
	
	increaseMatrix(i)
	// Green matrix
	var g: [Float] = Array(count: pix, repeatedValue: 0.0)
	vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &g, vDSP_Stride(1), vDSP_Length(g.count))
	
	increaseMatrix(i)
	// Blue matrix
	var b: [Float] = Array(count: pix, repeatedValue: 0.0)
	vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &b, vDSP_Stride(1), vDSP_Length(b.count))
	
	increaseMatrix(i)
	// Alpha matrix
	var a: [Float] = Array(count: pix, repeatedValue: 0.0)
	vDSP_vindex(&rawDataArray, &i, vDSP_Stride(1), &a, vDSP_Stride(1), vDSP_Length(a.count))
	
	return (r, g, b, a)
}`

**Comment by atveit** [comment]
This issue is closed by http://deeplearningkit.org/tutorials-for-ios-os-x-and-tvos/tutorial-image-handling-in-deeplearningkit/

**Comment by atveit** [comment]
Hi @several27 and @ashmanov - have added your code for UIImage conversion now, will update the recent blog post with this :-) Thanks! :+1: 

See https://github.com/DeepLearningKit/DeepLearningKit/commit/88faf0140b1ad0a0e1e83ed29057f2bdb34f7476
